### ISSUE TITLE
Nitrogen over Yaws set cookie throws exception

### ISSUE THREAD

**Issue by SserwangaV** [nitrogen/nitrogen#134]
I've installed Nitrogen over Yaws (Nitrogen 2.4.0, Yaws 2.0.8, ERTS 13.2 - R25).

When I try `http://0.0.0.0:8000/ ` I get **Internal server error.** When I check in the console I get this error.

```
{error,first_request,
    {url,"b_server/"},
    {throw,
        {badarg,same_site},
        [{yaws_api,cookie_option,2,[{file,"src/yaws_api.erl"},{line,725}]},
         {yaws_api,'-set_cookie/3-fun-0-',2,
             [{file,"src/yaws_api.erl"},{line,734}]},
         {lists,foldl,3,[{file,"lists.erl"},{line,1350}]},
         {yaws_api,set_cookie,3,[{file,"src/yaws_api.erl"},{line,733}]},
         {yaws_simple_bridge,'-assemble_headers/1-lc$^0/1-1-',1,
             [{file,"src/yaws_bridge_modules/yaws_simple_bridge.erl"},
              {line,215}]},
         {yaws_simple_bridge,assemble_headers,1,
             [{file,"src/yaws_bridge_modules/yaws_simple_bridge.erl"},
              {line,215}]},
         {yaws_simple_bridge,build_response,2,
             [{file,"src/yaws_bridge_modules/yaws_simple_bridge.erl"},
              {line,161}]},
         {wf_core,run,0,[{file,"src/wf_core.erl"},{line,23}]}]}}

```

**Comment by choptastic** [comment]
Ahh yes.

This was a bug, but it was pretty recently fixed.
It's a bug in simple_bridge, that was introduced in https://github.com/nitrogen/simple_bridge/commit/63cea4d072eb392dad8fa923907344506ad1ed70 and fixed in https://github.com/nitrogen/simple_bridge/commit/69247811dd0d6e5aa8007d56677309e1fff738cf
If you pull the latest version of simple_bridge, that should solve your problems.
Thanks!
Jesse Gumm
http://jessegumm.com

**Comment by lgmfred** [comment]
I'm having the same issue but pulling the latest `simple_bridge` doesn't seem to be working.

By default, the `rebar.config` files in both the project root directory and `nitrogen_core` repo pull the latest version (`{branch, master}`) but the bug still persists. As a temporary fix, I had to modify `./lib/nitrogen_core/rebar.config` to use the tag `v2.1.0`  of `simple_bridge`.

I'm also running Nitrogen 2.4.0 over Yaws. One on OTP 24 [erts-12.3.2.13] and another on OTP 25 [erts-13.2.2].

**Comment by lgmfred** [comment]
It turns out support for `SameSite` cookie was added in [Yaws 2.1.0](https://github.com/erlyaws/yaws/releases/tag/yaws-2.1.0), not the default Yaws 2.0.8. I just made the app to pull Yaws-2.1.0 and was back in business.

The app was using the latest commit on the master branch of [nitrogen_core@d00926a](https://github.com/nitrogen/nitrogen_core/commit/d00926a454be16b46ed1da8ca661524567ee1f7d), 
[Yaws 2.0.8](https://github.com/erlyaws/yaws/releases/tag/yaws-2.0.8) (which is the dafault one pulled), and also the latest commit on the master branch of [simple_bridge@7137f6a](https://github.com/nitrogen/simple_bridge/commit/7137f6a5ebd430353a6f3c19313a0a0d42b77797).

This was the error:

```
=INFO REPORT==== 19-Aug-2023::09:41:43.100499 ===
{error,first_request,
    {url,"localhost:8000/"},
    {throw,
        {badarg,same_site},
        [{yaws_api,cookie_option,2,[{file,"src/yaws_api.erl"},{line,725}]},
         {yaws_api,'-set_cookie/3-fun-0-',2,
             [{file,"src/yaws_api.erl"},{line,734}]},
         {lists,foldl,3,[{file,"lists.erl"},{line,1350}]},
         {yaws_api,set_cookie,3,[{file,"src/yaws_api.erl"},{line,733}]},
         {yaws_simple_bridge,'-assemble_headers/1-lc$^0/1-1-',1,
             [{file,"src/yaws_bridge_modules/yaws_simple_bridge.erl"},
              {line,215}]},
         {yaws_simple_bridge,assemble_headers,1,
             [{file,"src/yaws_bridge_modules/yaws_simple_bridge.erl"},
              {line,215}]},
         {yaws_simple_bridge,build_response,2,
             [{file,"src/yaws_bridge_modules/yaws_simple_bridge.erl"},
              {line,161}]},
         {wf_core,run,0,[{file,"src/wf_core.erl"},{line,23}]}]}}

=INFO REPORT==== 19-Aug-2023::09:41:43.101523 ===
Crash Handler Crashed:
{throw,{badarg,same_site},
       [{yaws_api,cookie_option,2,[{file,"src/yaws_api.erl"},{line,725}]},
        {yaws_api,'-set_cookie/3-fun-0-',2,
                  [{file,"src/yaws_api.erl"},{line,734}]},
        {lists,foldl,3,[{file,"lists.erl"},{line,1350}]},
        {yaws_api,set_cookie,3,[{file,"src/yaws_api.erl"},{line,733}]},
        {yaws_simple_bridge,'-assemble_headers/1-lc$^0/1-1-',1,
                            [{file,"src/yaws_bridge_modules/yaws_simple_bridge.erl"},
                             {line,215}]},
        {yaws_simple_bridge,assemble_headers,1,
                            [{file,"src/yaws_bridge_modules/yaws_simple_bridge.erl"},
                             {line,215}]},
        {yaws_simple_bridge,build_response,2,
                            [{file,"src/yaws_bridge_modules/yaws_simple_bridge.erl"},
                             {line,161}]},
        {wf_core,run_crash,4,[{file,"src/wf_core.erl"},{line,46}]}]}

Original Crash:
{throw,{badarg,same_site},
       [{yaws_api,cookie_option,2,[{file,"src/yaws_api.erl"},{line,725}]},
        {yaws_api,'-set_cookie/3-fun-0-',2,
                  [{file,"src/yaws_api.erl"},{line,734}]},
        {lists,foldl,3,[{file,"lists.erl"},{line,1350}]},
        {yaws_api,set_cookie,3,[{file,"src/yaws_api.erl"},{line,733}]},
        {yaws_simple_bridge,'-assemble_headers/1-lc$^0/1-1-',1,
                            [{file,"src/yaws_bridge_modules/yaws_simple_bridge.erl"},
                             {line,215}]},
        {yaws_simple_bridge,assemble_headers,1,
                            [{file,"src/yaws_bridge_modules/yaws_simple_bridge.erl"},
                             {line,215}]},
        {yaws_simple_bridge,build_response,2,
                            [{file,"src/yaws_bridge_modules/yaws_simple_bridge.erl"},
                             {line,161}]},
        {wf_core,run,0,[{file,"src/wf_core.erl"},{line,23}]}]}
```

**Comment by choptastic** [comment]
Oh, good to know!

Thanks!
